on:
  push:
    branches:
      - main
name: Deploy to retrorocket.biz
jobs:
  publish:
    name: Deploy to retrorocket.biz
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v1
      with:
        private-key: ${{ secrets.SSH_KEY }}
        public-key: ${{ secrets.SSH_KEY_PUBLIC }}
        known-hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Git pull
      run: ssh digitaling@digitaling.sakura.ne.jp
