name: Deploy to Server
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Execute deployment script
      uses: ./
      with:
        host: 'digitaling.sakura.ne.jp'
        username: 'digitaling'
        password: ${{ secrets.PASSWORD }}
        script: |
          whoami
          #cd /var/www/html
          #git pull origin main
          
